services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: user
      POSTGRES_PASSWORD: astra

  app:
    build: .
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: user
      POSTGRES_PASSWORD: astra
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    links:
      - db:database
    ports: ["8080:8080"]
# volumes:
  # pgdata: 